# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 1,2,4,8,16,24
numberOfSources: 1,1,2,4,6,8

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 65536
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 1048576

##benchmark parameter for the entire run
inputType: MemoryMode
sourceMode: wrapBuffer
sourcePinList: 0
workerPinList: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32

#For old runs
#sourcePinList: 0,1,2,3,16,17,18,19
#workerPinList: 4,5,6,7,8,9,10,11,12,13,14,15,20,21,22,23,24,25,26,27,28,29,30,31,36,37,38,39,40,41,42,43,44,45,46,47
#inputType: LambdaMode
#  4,5,6,7,20,21,22,23,8,9,10,11,24,25,26,27,12,13,14,15,28,29,30,31
outputFile: RepHalfTupleSize.csv
benchmarkName: RepHalfTupleSize
query: 'Query::from("input").project(Attribute("id"), Attribute("value")).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 500000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5