# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
#numberOfWorkerThreads: 1,2,4,8,15,16,24
numberOfWorkerThreads: 2
numberOfSources: 1
numberOfQueriesToDeploy: 2

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 16384
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
#bufferSizeInBytes: 1048576
bufferSizeInBytes: 131072

##benchmark parameter for the entire run
dataGenerator: Default
numberOfPreAllocatedBuffer: 1000
logicalStreamName: input
dataProvider: External
dataProviderMode: ZeroCopy
ingestionRateList: 50000,50000
ingestionDistributionList: SINUS,COSINUS
#gatheringValues: 11000 #is one 100M tuples

sourcePinList: 0,1,2,3
workerPinList: 4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
queuePinList: 0,1

outputFile: RepReadOnlyOneSourceMultiQueryHistory.csv
benchmarkName: RepReadOnlyOneSourceMultiQueryHistory
query: 'Query::from("input").filter(Attribute("value") > 10000).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 500000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 30
collectionMode: History
