# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 8
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 20000
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 1048576

##benchmark parameter for the entire run
inputType: WindowMode
outputFile: OneStreamFillingAndFireing.csv
benchmarkName: OneStreamFillingAndFireing
# we trigger the window each 1 million records
query: 'Query::from("input").window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(10000000))).byKey(Attribute("id")).apply(Sum(Attribute("value"))).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 5000000
scalability: scale-up
logLevel: LOG_DEBUG
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5