# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
numberOfWorkerThreads: 8
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 20000
numberOfBuffersPerPipeline: 10
numberOfBuffersInSourceLocalBufferPool: 1000
bufferSizeInBytes: 1048576

##benchmark parameter for the entire run
inputType: WindowMode
outputFile: OneStreamOnlyFilling.csv
benchmarkName: OneStreamOnlyFilling
# We set the window size to 100000000 such that we never emit a tuple.
query: 'Query::from("input").window(TumblingWindow::of(EventTime(Attribute("timestamp")), Seconds(100000000))).byKey(Attribute("id")).apply(Sum(Attribute("value"))).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 5000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5