# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
numberOfSources: 1
#numberOfQueriesToDeploy: 2,4,8
#numberOfWorkerThreads: 16,16,16
#numberOfThreadsPerQueue: 8,4,2
queryManagerMode: Static
#numberOfQueues:
numberOfQueriesToDeploy: 128
numberOfWorkerThreads: 128
#DYNAMIC CONFIG
#queryManagerMode: Dynamic
#numberOfWorkerThreads: 16
#sourceSharing: true

#STATIC CONFIG
#numberOfWorkerThreads: 8,16,24,32,40,48,56,64
##numberOfWorkerThreads: 32,40,48,56,64

numberOfThreadsPerQueue: 1
#sourceToQueueMapList: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64

# engine configuration  1048576
#numberOfBuffersInGlobalBufferManager: 131072
numberOfBuffersInGlobalBufferManager: 362144
numberOfBuffersPerPipeline: 128
numberOfBuffersInSourceLocalBufferPool: 128
bufferSizeInBytes: 1048576
#bufferSizeInBytes: 131072

##benchmark parameter for the entire run
dataGenerator: YSB
numberOfPreAllocatedBuffer: 1000
logicalStreamName: ysb
dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: YSBQueryMulti.csv
benchmarkName: YSBQueryMulti
query: 'Query::from("ysb").filter(Attribute("event_type") < 1).window(TumblingWindow::of(EventTime(RecordCreationTs()), Seconds(30))).byKey(Attribute("campaign_id")).apply(Sum(Attribute("user_id"))).sink(NullOutputSinkDescriptor::create());'

#benchmark internal parameter
numberOfBuffersToProduce: 5000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5