# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list
#numberOfWorkerThreads: 2
numberOfSources: 1
#sourcePinList:
#workerPinList: 1,2

#numberOfWorkerThreads: 2
#numberOfQueriesToDeploy: 2
#sourceSharing: true
queryManagerMode: Static
numberOfThreadsPerQueue: 1
numberOfWorkerThreads: 2
numberOfQueriesToDeploy: 2

#numberOfQueriesToDeploy: 2
#numberOfWorkerThreads: 16
#numberOfThreadsPerQueue: 8


# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 10240
#numberOfBuffersInGlobalBufferManager: 10240
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 131072

##benchmark parameter for the entire run
dataGenerator: Default
numberOfPreAllocatedBuffer: 100
logicalStreamName: input
dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: YSBQuery.csv
benchmarkName: YSBQuery
#query: 'Query::from("ysb").filter(Attribute("event_type") < 1).window(TumblingWindow::of(EventTime(Attribute("timestamp")), Seconds(30))).byKey(Attribute("campaign_id")).apply(Sum(Attribute("user_id"))).sink(NullOutputSinkDescriptor::create());'

query: 'Query::from("input").filter(Attribute("value") > 10000).sink(NullOutputSinkDescriptor::create());'
#benchmark internal parameter
numberOfBuffersToProduce: 5000000
scalability: scale-up
logLevel: LOG_DEBUG
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 3
numberOfMeasurementsToCollect: 5