# ~~~ Configurations for the NES Coordinator ~~~

# ~~ IPs and Ports ~~
# Set NES ip of the REST server
#restIp: 127.0.0.1

# Set RPC IP or host of NES Coordinator
#coordinatorHost: 127.0.0.1

# Set RPC Server port of NES Coordinator
#rpcPort: 4000

# Set port exposed for REST endpoints
#restPort: 8081

# Set the data port of the network manager
#dataPort: 3001


# ~~ Processing Configurations ~~
# Set the number of computing slots in NES Coordinator
#numberOfSlots: 65535

# The log level (LOG_NONE, LOG_WARNING, LOG_DEBUG, LOG_INFO, LOG_TRACE)
#logLevel: LOG_DEBUG

# Number buffers in global buffer pool
#numberOfBuffersInGlobalBufferManager: 1024

# Number buffers in task local buffer pool
#numberOfBuffersPerWorker: 128

# Number buffers in source local buffer pool
#numberOfBuffersInSourceLocalBufferPool: 64

# Size of buffer to pass data through the system
#bufferSizeInBytes: 4096

# Number of threads available for the worker node. Defines how many queries can run in parallel.
#numWorkerThreads: 1

# The number of queries to be processed together
#queryBatchSize: 1

# Enable monitoring
#enableMonitoring: false

# Enable reconfiguration of running query plans. Default: false
#enableQueryReconfiguration:

optimizer:
  # The rule to be used for performing query merging
  #queryMergerRule: DefaultQueryMergerRule

  # Advance Semantic Query Validation Feature
  #advanceSemanticValidation: false

  # Selects the memory layout selection policy can be [FORCE_ROW_LAYOUT|FORCE_COLUMN_LAYOUT]
  #memoryLayoutPolicy: FORCE_ROW_LAYOUT

  # Perform only source operator duplication when applying Logical Source Expansion Rewrite Rule
  #performOnlySourceOperatorExpansion: false

  # The number of queries to be processed together
  #queryBatchSize: 1

  # Perform only source operator duplication when applying Logical Source Expansion Rewrite Rule.
  #performOnlySourceOperatorExpansion: false

# Set a single logical source with multiple fields in the schema
# Valid types are: INT8, UINT8, INT16, UINT16, INT32, UINT32, INT64, FLOAT32, UINT64, FLOAT64, BOOLEAN, CHAR
# CHARS require the length key
# FLOAT32 is float, FLOAT64 is double
#logicalSources:
#  - logicalSourceName: "default_logical"
#    fields:
#      - name: "id"
#        type: "UINT32"
#      - name: "value"
#        type: "UINT64"
#      - name: "char_value"
#        type: "CHAR"
#        length: 5