# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1
numberOfQueriesToDeploy: 1,2,4,8,16
sourceSharing: off
numberOfBuffersInGlobalBufferManager: 98304
numberOfBuffersPerPipeline: 128
numberOfBuffersInSourceLocalBufferPool: 128
bufferSizeInBytes: 131072
connectionString: "10.156.0.30:9092,nesKafka,0"
numberOfPreAllocatedBuffer: 10
batchSize: 10

# ~~~ Benchmark parameter for the entire run ~~~
numberOfBuffersToProduce: 200000
logLevel: LOG_DEBUG
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 0
numberOfMeasurementsToCollect: 5

logicalSources:
  input1:
    type: YSBKafka
    numberOfPhysicalSources: 1

dataProviderMode: ZeroCopy
outputFile: YSBQuery.csv
benchmarkName: YSBQuery
query: 'Query::from("ysb").filter(Attribute("event_type") < 1).window(TumblingWindow::of(EventTime(RecordCreationTs()), Seconds(30))).byKey(Attribute("campaign_id")).apply(Sum(Attribute("user_id"))).sink(NullOutputSinkDescriptor::create());'
#query: 'Query::from("ysb").filter(Attribute("event_type") < 1).window(TumblingWindow::of(EventTime(Attribute("current_ms")), Seconds(30))).byKey(Attribute("campaign_id")).apply(Sum(Attribute("user_id"))).sink(NullOutputSinkDescriptor::create());'
#query: 'Query::from("ysb").filter(Attribute("event_type") < 1).sink(NullOutputSinkDescriptor::create());'