###
### General configuration
###
logLevel: LOG_ERROR
#logLevel: LOG_WARNING
#logLevel: LOG_DEBUG

###
### Network configuration
###
localWorkerHost: 172.31.0.3
coordinatorHost: coordinator

###
### Physical source configuration
###
physicalSources:
    - logicalSourceName: can_bus
      physicalSourceName: can_bus_csv
      type: CSV_SOURCE
      configuration:
          filePath: /tutorial/0917-619-30-s.csv
          delimiter: "*"
          numberOfBuffersToProduce: 1024
          numberOfTuplesToProducePerBuffer: 0
          skipHeader: true
queryCompiler:
    queryCompilerType: "NAUTILUS_QUERY_COMPILER"
    windowingStrategy: THREAD_LOCAL
