# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1, 2, 4
bufferSizeInBytes: 5120, 5120, 5120
numberOfPreAllocatedBuffer: 10000000

# ~~~ Benchmark parameter for the entire run ~~~
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 1
numberOfMeasurementsToCollect: 3

logicalSources:
  - name: input1
    type: Default

  - name: input2
    type: Uniform
    minValue: 0
    maxValue: 250

  - name: input3
    type: Zipfian
    alpha: 0.99
    minValue: 0
    maxValue: 1000

inputType: MemoryMode
dataProviderMode: MemCopy
outputFile: JoinMultipleSources.csv
benchmarkName: JoinMultipleSources
query: 'Query::from("input1").joinWith(Query::from("input2"))
                                  .where(Attribute("value") == Attribute("value"))
                                  .window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(500)))
                             .joinWith(Query::from("input3"))
                                  .where(Attribute("value") == Attribute("value"))
                                  .window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(500)))
                             .sink(NullOutputSinkDescriptor::create());'