# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1, 2, 4, 1, 2, 4
bufferSizeInBytes: 5120, 5120, 5120, 10240, 10240, 10240
numberOfPreAllocatedBuffer: 10000000

# ~~~ Benchmark parameter for the entire run ~~~
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 1
numberOfMeasurementsToCollect: 3

logicalSources:
  - name: input1
  - name: input2
  - name: input3

inputType: MemoryMode
dataProviderMode: MemCopy
outputFile: JoinTwoSources.csv
benchmarkName: JoinTwoSources
query: 'Query::from("input1").joinWith(Query::from("input2"))
                                  .where(Attribute("id") == Attribute("id"))
                                  .window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(500)))
                             .joinWith(Query::from("input3"))
                                  .where(Attribute("id") == Attribute("id"))
                                  .window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(500)))
                             .sink(NullOutputSinkDescriptor::create());'