# ~~~ Configurations for the NES E2E Benchmark ~~~
numberOfWorkerThreads: 1
bufferSizeInBytes: 131072
numberOfPreAllocatedBuffer: 100
numberOfBuffersToProduce: 5000000


# ~~~ Benchmark parameter for the entire run ~~~
logLevel: LOG_INFO
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 1
numberOfMeasurementsToCollect: 10

logicalSources:
  - name: input1
    type: Default

  - name: input2
    type: Zipfian
    numberOfPhysicalSources: 1
    alpha: 0.99
    minValue: 0
    maxValue: 1000

inputType: MemoryMode
dataProviderMode: MemCopy
outputFile: JoinTwoSources.csv
benchmarkName: JoinTwoSources
query: 'Query::from("input1").joinWith(Query::from("input2"))
                                  .where(Attribute("value") == Attribute("value"))
                                  .window(TumblingWindow::of(EventTime(Attribute("timestamp")), Milliseconds(500)))
                             .sink(NullOutputSinkDescriptor::create());'