FROM nebulastream/nes-build-image:latest

# install a debugger and the second CLion-supported build system
RUN DEBIAN_FRONTEND="noninteractive" apt-get update -qq && apt-get install -qq \
  gdb \
  ninja-build \
&& apt-get clean -qq

ADD install-profiler.sh /install-profiler.sh
