#Location of query set
# For each query set we will run the experiments
QuerySetLocation: '<query set location>'
# LOG level
LogLevel: LOG_ERROR
# Sleep interval between each run
StartupSleepIntervalInSeconds: 3
# Number of times experiment is to be repeated
NumOfRuns: 1
# Initial number of queries to deploy
InitialQueries: 4096

RunConfig:
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 0
    NumOfAddQueries: 16
    ConfNum: 1
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 2
    NumOfAddQueries: 14
    ConfNum: 2
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 4
    NumOfAddQueries: 12
    ConfNum: 3
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 8
    NumOfAddQueries: 8
    ConfNum: 4
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 0
    NumOfAddQueries: 16
    ConfNum: 5
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 2
    NumOfAddQueries: 14
    ConfNum: 6
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 4
    NumOfAddQueries: 12
    ConfNum: 7
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 16
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 16
    NumOfRemoveQueries: 8
    NumOfAddQueries: 8
    ConfNum: 8
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 0
    NumOfAddQueries: 32
    ConfNum: 9
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 2
    NumOfAddQueries: 30
    ConfNum: 10
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 4
    NumOfAddQueries: 28
    ConfNum: 11
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 8
    NumOfAddQueries: 24
    ConfNum: 12
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 16
    NumOfAddQueries: 16
    ConfNum: 13
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 0
    NumOfAddQueries: 32
    ConfNum: 14
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 2
    NumOfAddQueries: 30
    ConfNum: 15
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 4
    NumOfAddQueries: 28
    ConfNum: 16
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 8
    NumOfAddQueries: 24
    ConfNum: 17
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: true
    PlacementAmendmentThreadCount: 32
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 32
    NumOfRemoveQueries: 16
    NumOfAddQueries: 16
    ConfNum: 18
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 1
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 1
    NumOfRemoveQueries: 0
    NumOfAddQueries: 32
    ConfNum: 19
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 1
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 1
    NumOfRemoveQueries: 2
    NumOfAddQueries: 30
    ConfNum: 20
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 1
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 1
    NumOfRemoveQueries: 4
    NumOfAddQueries: 28
    ConfNum: 21
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 1
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 1
    NumOfRemoveQueries: 8
    NumOfAddQueries: 24
    ConfNum: 22
  - QueryPlacementStrategy: BottomUp
    IncrementalPlacement: false
    PlacementAmendmentThreadCount: 1
    PlacementAmendmentMode: OPTIMISTIC
    BatchSize: 1
    NumOfRemoveQueries: 16
    NumOfAddQueries: 16
    ConfNum: 23


