###
### General configuration
###
#logLevel: LOG_ERROR
#logLevel: LOG_WARNING
logLevel: LOG_DEBUG
optimizer:
        distributedWindowChildThreshold: 3

###
### Network configuration
###
restIp: 172.31.0.2
coordinatorHost: 172.31.0.2
restPort: 8081

###
### Logical source configuration
###
logicalSources:
        - logicalSourceName: "qrs_peaks"
          fields:
                  - name: amp_r
                    type: CHAR
                    length: 1
                  - name: amp_r_ms
                    type: FLOAT64
                  - name: amp_r_val
                    type: FLOAT32
                  - name: amp_q
                    type: CHAR
                    length: 1
                  - name: amp_q_ms
                    type: FLOAT64
                  - name: amp_q_val
                    type: FLOAT32
                  - name: amp_s
                    type: CHAR
                    length: 1
                  - name: amp_s_ms
                    type: FLOAT64
                  - name: amp_s_val
                    type: FLOAT32

        - logicalSourceName: "qrs_features"
          fields:
            - name: qrs_peaks$ts
              type: FLOAT64
            - name: qrs_peaks$f1
              type: FLOAT32
            - name: qrs_peaks$f2
              type: FLOAT32
            - name: qrs_peaks$f3
              type: FLOAT32
            - name: qrs_peaks$f4
              type: FLOAT32
            - name: qrs_peaks$f5
              type: FLOAT32
            - name: qrs_peaks$f6
              type: FLOAT32
            - name: qrs_peaks$f7
              type: FLOAT32
            - name: qrs_peaks$f8
              type: FLOAT32
            - name: qrs_peaks$f9
              type: FLOAT32
            - name: qrs_peaks$f10
              type: FLOAT32
