###
### General configuration
###
#logLevel: LOG_ERROR
#logLevel: LOG_WARNING
logLevel: LOG_DEBUG

###
### Network configuration
###
localWorkerHost: 172.31.0.3
coordinatorHost: coordinator

###
### Physical source configuration
###
physicalSources:
#        - logicalSourceName: qrs_peaks
#          physicalSourceName: qrs_peaks_test
#          type: CSVSource
#          configuration:
#            filePath: /tutorial/qrs_peaks_test.csv
#            numberOfBuffersToProduce: 1000000
#            numberOfTuplesToProducePerBuffer: 0
#            skipHeader: true

        - logicalSourceName: qrs_peaks
          physicalSourceName: qrs_peaks_mqtt
          type: MQTT_SOURCE
          configuration:
            url: ws://10.0.0.11:9001
            clientId: admin_qrs
            inputFormat: CSV
            topic: qrs_peaks
            userName: admin
            qos: 2
            cleanSession: true
            flushIntervalMS: 100

#        - logicalSourceName: qrs_features
#          physicalSourceName: qrs_features_test
#          type: CSVSource
#          configuration:
#            filePath: /tutorial/qrs_features_test.csv
#            numberOfBuffersToProduce: 1000000
#            numberOfTuplesToProducePerBuffer: 0
#            skipHeader: true
#            
        - logicalSourceName: qrs_features
          physicalSourceName: qrs_features_mqtt
          type: MQTT_SOURCE
          configuration:
            url: ws://10.0.0.11:9001
            clientId: admin_qrs
            inputFormat: JSON
            topic: qrs_features
            userName: admin
            qos: 2
            cleanSession: true
            flushIntervalMS: 100

queryCompiler:
  windowingStrategy: THREAD_LOCAL
