###
### General configuration
###
logLevel: LOG_ERROR

# Disable distributed aggregation; work around for https://github.com/nebulastream/nebulastream/issues/2739
#optimizer:
#  distributedWindowChildThreshold: 3
optimizer:
        distributedWindowChildThreshold: 0
#        distributedWindowCombinerThreshold: 100

#worker:
#        queryCompiler.windowingStrategy: THREAD_LOCAL
#worker:
#  queryCompiler:
#    windowingStrategy: THREAD_LOCAL


###
### Network configuration
###
restIp: 172.32.0.21
coordinatorHost: 172.32.0.21
restPort: 8085
#workerConfigPath: /demo/conf/worker-w-1-coordinator.yml

###
### Logical source configuration
###
logicalSources:
  - logicalSourceName: "lora_stream"
    fields:
      - name: index
        type: UINT64
      - name: chan
        type: UINT32
      - name: datr
        type: CHAR
        length: 50
      - name: devaddr
        type: CHAR
        length: 50
      - name: deveui
        type: UINT64
      - name: freq
        type: FLOAT32
      - name: gwmac
        type: CHAR
        length: 50
      - name: lsnr
        type: FLOAT32
      - name: ns_time
        type: CHAR
        length: 50
      - name: rssi
        type: FLOAT32
      - name: size
        type: FLOAT32
      - name: time
        type: CHAR
        length: 50
      - name: tmst
        type: UINT64
      - name: ftype
        type: UINT64
      - name: fcnt
        type: UINT64
      - name: agent_time
        type: UINT64
      - name: end_line
        type: UINT64
  - logicalSourceName: "wdn_stream"
    fields:
      - name: index
        type: UINT64
      - name: hour
        type: UINT64
        #type: CHAR
        #length: 30
      - name: nodeID
        type: UINT64
      - name: demand_value
        type: FLOAT32
      - name: head_value
        type: FLOAT32
      - name: pressure_value
        type: FLOAT32
      - name: x_pos
        type: FLOAT32
      - name: y_pos
        type: FLOAT32
      - name: node_type
        type: UINT64
      - name: has_leak
        type: CHAR
        length: 30
      - name: leak_area_value
        type: FLOAT32
      - name: leak_discharge_value
        type: FLOAT32
      - name: current_leak_demand_value
        type: FLOAT32
      - name: smart_sensor_is_present
        type: FLOAT32
      - name: tmst
        type: UINT64
      - name: dateTime
        type: CHAR
        length: 30
      - name: dev_addr
        type: CHAR
        length: 30
      - name: dev_eui
        type: CHAR
        length: 30
      - name: gateway
        type: UINT64
      - name: endLine
        type: UINT64
  - logicalSourceName: "wdn_stream_l"
    fields:
      - name: index
        type: UINT64
      - name: hour
        type: CHAR
        length: 30
      - name: nodeID
        type: CHAR
        length: 30
      - name: demand_value
        type: FLOAT32
      - name: head_value
        type: FLOAT32
      - name: pressure_value
        type: FLOAT32
      - name: x_pos
        type: FLOAT32
      - name: y_pos
        type: FLOAT32
      - name: node_type
        type: UINT64
      - name: has_leak
        type: CHAR
        length: 30
      - name: leak_area_value
        type: FLOAT32
      - name: leak_discharge_value
        type: FLOAT32
      - name: current_leak_demand_value
        type: FLOAT32
      - name: smart_sensor_is_present
        type: FLOAT32
      - name: tmst
        type: UINT64
      - name: dateTime
        type: CHAR
        length: 30
      - name: dev_addr
        type: CHAR
        length: 30
      - name: dev_eui
        type: CHAR
        length: 30
      - name: gateway
        type: CHAR
        length: 30
      - name: endLine
        type: UINT64