# ~~~ Configurations for the NES E2E Benchmark ~~~

benchmarkName: ClusterMonitoring1
outputFile: clustermonitoring1.csv

#numberOfWorkerThreads: 1,2,3,4,5,6,7,8
#numberOfSources: 1,1,1,1,2,2,2,2
numberOfWorkerThreads: 1,2,4,8,16
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 8196
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 1048576
#bufferSizeInBytes: 131072

# configure data source
numberOfPreAllocatedBuffer: 100

logicalSources:
  - name: cm
    type: ClusterMonitoring
dataProvider: Internal
dataProviderMode: ZeroCopy

query: 'Query::from("cm").window(SlidingWindow::of(EventTime(RecordCreationTs()), Seconds(60), Seconds(1))).apply(Sum(Attribute("cpu"))->as(Attribute("totalCpu"))).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 10000
#generatorPinList: 12
#sourcePinList: 0
#workerPinList: 1,2,3,4,5,6,7,8,9,10

#benchmark internal parameter
numberOfBuffersToProduce: 500000000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10