# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list // sources needs to be edited.
#numberOfWorkerThreads: 1,2,3,4,5,6,7,8
#numberOfSources: 1,1,1,1,2,2,2,2
numberOfWorkerThreads: 1,2,4,8,16
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 8196
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 1048576
#bufferSizeInBytes: 131072

##benchmark parameter for the entire run
numberOfPreAllocatedBuffer: 100

logicalSources:
  - name: lrb
    type: LinearRoad

dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: linearroadbenchmark1.csv
benchmarkName: LinearRoadBenchmark1
#original
query: 'Query::from("lrb").map(Attribute("position") = Attribute("position")/5280).window(SlidingWindow::of(EventTime(RecordCreationTs()), Seconds(300), Seconds(1))).byKey(Attribute("highway"), Attribute("direction"), Attribute("position")).apply(Avg(Attribute("speed"))->as(Attribute("avgSpeed"))).filter(Attribute("avgSpeed") < 40).sink(NullOutputSinkDescriptor::create());'
#query: 'Query::from("lrb").map(Attribute("position") = Attribute("position")/5280).window(SlidingWindow::of(EventTime(RecordCreationTs()), Seconds(300), Seconds(1))).byKey(Attribute("highway")).apply(Avg(Attribute("speed"))->as(Attribute("avgSpeed"))).filter(Attribute("avgSpeed") < 40).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 50000
#generatorPinList: 11
#sourcePinList: 0
#workerPinList: 1,2,3,4,5,6,7,8,9,10

#benchmark internal parameter
numberOfBuffersToProduce: 500000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10