# ~~~ Configurations for the NES E2E Benchmark ~~~

# Parameter that are changed per run with comma separated list // sources needs to be edited.
#numberOfWorkerThreads: 1,2,3,4,5,6,7,8
#numberOfSources: 1,1,1,1,2,2,2,2
numberOfWorkerThreads: 1,2,4,8,16
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 8192
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 1048576
#bufferSizeInBytes: 131072

##benchmark parameter for the entire run
numberOfPreAllocatedBuffer: 100
logicalSources:
  - name: me
    type: ManufacturingEquipment

dataProvider: Internal
dataProviderMode: ZeroCopy
outputFile: manufacturingequipment1.csv
benchmarkName: ManufacturingEquipment1
#ORIGINAL
query: 'Query::from("me").window(SlidingWindow::of(EventTime(RecordCreationTs()), Seconds(60), Seconds(1))).apply(Avg(Attribute("mf01"))->as(Attribute("avg_mf01")), Avg(Attribute("mf02"))->as(Attribute("avg_mf02")), Avg(Attribute("mf03"))->as(Attribute("avg_mf03"))).sink(NullOutputSinkDescriptor::create());'
#query: 'Query::from("me").window(SlidingWindow::of(EventTime(RecordCreationTs()), Seconds(60), Seconds(1))).apply(Avg(Attribute("mf01"))->as(Attribute("avg_mf01"))).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 50000
#generatorPinList: 12
#sourcePinList: 0
#workerPinList: 1,2,3,4,5,6,7,8,9,10

#benchmark internal parameter
numberOfBuffersToProduce: 100000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10