# ~~~ Configurations for the NES E2E Benchmark ~~~

benchmarkName: Nexmark2
outputFile: nexmark2.csv

#numberOfWorkerThreads: 1,2,3,4,5,6,7,8
#numberOfSources: 1,1,1,1,2,2,2,2
numberOfWorkerThreads: 1,2,4,8,16
numberOfSources: 1

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 65536
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
#bufferSizeInBytes: 1048576
bufferSizeInBytes: 131072

logicalSources:
  - name: bit
    type: NEBit


dataProvider: Internal
dataProviderMode: ZeroCopy


query: 'Query::from("bit").filter(Attribute("auctionId") == 1007 || Attribute("auctionId") == 1020 || Attribute("auctionId") == 2001 || Attribute("auctionId") == 2019 || Attribute("auctionId") == 2087).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 10000
#generatorPinList: 12
#sourcePinList: 0
#workerPinList: 1,2,3,4,5,6,7,8,9,10

#benchmark internal parameter
numberOfBuffersToProduce: 500000000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10