# ~~~ Configurations for the NES E2E Benchmark ~~~

benchmarkName: Nexmark1
outputFile: nexmark1.csv

numberOfWorkerThreads: 1,2,4,8,16
numberOfSources: 1,2

# engine configuration parameter
numberOfBuffersInGlobalBufferManager: 65536
numberOfBuffersPerPipeline: 1024
numberOfBuffersInSourceLocalBufferPool: 1024
bufferSizeInBytes: 131072

logicalSources:
  - name: bit
    type: NEBit

logicalStreamName: bit
numberOfPreAllocatedBuffer: 1000
dataProvider: Internal
dataProviderMode: ZeroCopy

query: 'Query::from("bit").map(Attribute("price") = Attribute("price") * 89 / 100).sink(NullOutputSinkDescriptor::create());'

gatheringValues: 10000
#generatorPinList: 12
#sourcePinList: 0
#workerPinList: 1,2,3,4,5,6,7,8,9,10

#benchmark internal parameter
numberOfBuffersToProduce: 500000000000
scalability: scale-up
logLevel: LOG_NONE
experimentMeasureIntervalInSeconds: 1
startupSleepIntervalInSeconds: 5
numberOfMeasurementsToCollect: 10