name: NES Benchmark

# A benchmark should be triggered, whenever a new version is released or when the workflow is manually dispatched
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      trigger-value:
        description: 'Trigger for performing benchmark on artifact release'
        required: false
        default: 'No_Value'

jobs:
  benchmark-scheduled-job:
    runs-on: [self-hosted, linux, X64, Benchmark]
    timeout-minutes: 60
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.CI_SECRET }}
          ssh-strict: 'false'
      - name: Run benchmarks
        run: |
          docker run --name ${{ github.run_id }}_benchmark_version -v $GITHUB_WORKSPACE:/nebulastream -v /etc/localtime:/etc/localtime:ro --entrypoint /nebulastream/docker/buildImage/entrypoint-nes-benchmark.sh nebulastream/nes-build-image:latest
      - name: Push Benchmarks to pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token:  ${{ secrets.CI_TOKEN }}
          publish_dir: results
          destination_dir: benchmark/
          exclude_assets: '*.py,*.so'
          keep_files: true
          external_repository: nebulastream/benchmark-data
          publish_branch: master
      - name: docker cleanup
        if: ${{ always() }}
        run: |
          docker rm -f ${{ github.run_id }}_benchmark_version