name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '37 17 * * *'

jobs:
  stale:

    runs-on: [ self-hosted, linux, X64, Build ]
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.CI_PRIVILEGE_SECRETE }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-close: -1

